### ISSUE TITLE
App will crash when opening without Discord running in the background.

### ISSUE THREAD

**Issue by XandrCopyrighted** [XandrCopyrighted/Cazic#13]
Using Windows

**Comment by WilliamAnimate** [comment]
~~skill issue; migrate to linux~~

alr fixing rn

**Comment by WilliamAnimate** [comment]
![image](https://github.com/XandrCopyrighted/Cazic/assets/75321465/3199ec28-21cc-43da-a6c4-844a68b56843)

its been a while since i've actually properly used this text editor (2 days)
im gonna be *rusty* with it (:laughing: :rofl: :smile: :hahahahewherfhrf:)

(also is it weird to navigate the document with the arrow keys rather than hjkl lol)

**Comment by WilliamAnimate** [comment]
![image](https://github.com/XandrCopyrighted/Cazic/assets/75321465/e20a0532-a4d5-42c1-8364-7693e1f10f66)

it does panic, but the app doesn't crash... i'd assume its `panic=abort` quitting the app.

**Comment by XandrCopyrighted** [comment]
ah

**Comment by XandrCopyrighted** [comment]
Updating `Cargo.toml` and closing

**Comment by XandrCopyrighted** [comment]
update: no need to edit Cargo.toml, it's fixed
